src/AppBundle/Entity/Paciente.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Paciente
 *
 * @ORM\Table(name="paciente")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PacienteRepository")
 */
class Paciente
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nome", type="string", length=255)
     */
    private $nome;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nome
     *
     * @param string $nome
     *
     * @return Paciente
     */
    public function setNome($nome)
    {
        $this->nome = $nome;

        return $this;
    }

    /**
     * Get nome
     *
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }

    public function __toString()
    {
        return $this->nome;
    }
}

src/AppBundle/Entity/Procedimento.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Procedimento
 *
 * @ORM\Table(name="procedimento")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ProcedimentoRepository")
 */
class Procedimento
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nome", type="string", length=255, nullable=true)
     */
    private $nome;

    /**
     * @var string
     *
     * @ORM\Column(name="tempo_estimado", type="string", length=255, nullable=true)
     */
    private $tempoEstimado;

    /**
     * ORM\ManyToOne(targetEntity="Paciente")
     * ORM\JoinColumn(name="paciente_id", referencedColumnName="id")
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $paciente;

    /**
     * @ORM\ManyToOne(targetEntity="Setor")
     * ORM\JoinColumn(name="setor_id", referencedColumnName="id")
     * ORM\Column(name="setor", type="integer", nullable=true)
     */
    private $setor;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Set nome
     *
     * @param string $nome
     *
     * @return Procedimento
     */
    public function setNome($nome)
    {
        $this->nome = $nome;

        return $this;
    }

    /**
     * Get nome
     *
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }

    /**
     * Set tempoEstimado
     *
     * @param string $tempoEstimado
     *
     * @return Procedimento
     */
    public function setTempoEstimado($tempoEstimado)
    {
        $this->tempoEstimado = $tempoEstimado;

        return $this;
    }

    /**
     * Get tempoEstimado
     *
     * @return string
     */
    public function getTempoEstimado()
    {
        return $this->tempoEstimado;
    }

    /**
     * @return mixed
     */
    public function getPaciente()
    {
        return $this->paciente;
    }

    /**
     * @param mixed $paciente
     */
    public function setPaciente($paciente)
    {
        $this->paciente = $paciente;
    }



    /**
     * Set setor
     *
     * @param \AppBundle\Entity\Setor $setor
     *
     * @return Procedimento
     */
    public function setSetor($setor = null)
    {
        $this->setor = $setor;

        return $this;
    }

    /**
     * Get setor
     *
     * @return \AppBundle\Entity\Setor
     */
    public function getSetor()
    {
        return $this->setor;
    }

    public function __toString()
    {
        return $this->paciente?$this->paciente.' - '.$this->getSetor().$this->getNome():'';
    }
}

src/AppBundle/Entity/Setor.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Setor
 *
 * @ORM\Table(name="setor")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SetorRepository")
 */
class Setor
{
    const ENCAMINHADO = 4;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nome", type="string", length=255)
     */
    private $nome;

    public function setId($id){
        $this->id = $id;
    }
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }

    /**
     * @param string $nome
     */
    public function setNome($nome)
    {
        $this->nome = $nome;
    }

    public function getImageName(){
        $valor = strtolower(str_replace(" ","_",preg_replace("/&([a-z])[a-z]+;/i", "$1", htmlentities(trim($this->nome)))));
        return $valor?$valor:"";
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->nome?$this->nome:"";
    }
}

src/AppBundle/Entity/Setores.php
<?php

namespace AppBundle\Entity;




class Setores
{
    const RECEPCAO = 1;
    const SALA_OPERATORIA = 2;
    const RPA = 4;
    const LEITO = 8;


    protected static $choices = [
        self::RECEPCAO    => 'Recepção',
        self::SALA_OPERATORIA => 'Sala Operatória',
        self::RPA          => 'Recuperação',
        self::LEITO    => 'Encaminhado ao Leito',
    ];

    /**
     * @return array
     */
    public static function getChoices()
    {
        return self::$choices;
    }
}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Procedimento;
use AppBundle\Entity\Setor;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    const NUMBER_ITEMS = 12;
    const TOTAL_LIMIT = 12*3;
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        $pacientes = $this->getDoctrine()->getRepository(Procedimento::class )->findBy([],['setor'=>'ASC','id'=>'DESC'],self::TOTAL_LIMIT);
        $pages = ceil(count($pacientes)/self::NUMBER_ITEMS);
        return $this->render('@App/Default/pacientes.html.twig',['acompanhamentos'=>$pacientes,'pages'=>$pages,'number_item'=>self::NUMBER_ITEMS]);
    }

    /**
     * @Route("/atualiza", name="atualiza")
     */
    public function atualizaPacientesAction(Request $request){
        $pacientes = $this->getDoctrine()->getRepository(Procedimento::class )->findBy([],['setor'=>'ASC','id'=>'DESC'],self::TOTAL_LIMIT);
        $pages = ceil(count($pacientes)/self::NUMBER_ITEMS);
        return $this->render('@App/Default/pacientes.html.twig',['acompanhamentos'=>$pacientes,'pages'=>$pages,'number_item'=>self::NUMBER_ITEMS]);
    }
}

src/AppBundle/Controller/ProcedimentoCRUDController.php
<?php
// src/AppBundle/Controller/MediaCRUDController.php

namespace AppBundle\Controller;

use Sonata\AdminBundle\Controller\CRUDController;

class ProcedimentoCRUDController extends CRUDController
{
}

src/AppBundle/Tests/Controller/DefaultControllerTest.php
<?php

namespace AppBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/');

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
        $this->assertContains('Welcome to Symfony', $crawler->filter('#container h1')->text());
    }
}

src/AppBundle/Resources/views/Default/index.html.twig
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Acompanhamento</title>
    <link href="{{ asset('bundles/app/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/app/css/font-awesome.min.css') }}" rel="stylesheet"
          type="text/css">
    <link href="{{ asset('bundles/app/css/styles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/avanzuadmintheme/static/dev/styles/admin-lte-all.css') }}" rel="stylesheet"
          type="text/css">
    <script type="text/javascript" src="{{ asset('bundles/app/js/jquery-1.11.0.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/app/js/jquery-migrate-1.2.1.min.js') }}"></script>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/app/css/slick.css') }}"/>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css"
          href="{{ asset('bundles/app/css/slick-theme.css') }}"/>
    <script type="text/javascript" src="{{ asset('bundles/app/js/slick.min.js') }}"></script>
    {#<script src="{{ asset('bundles/sonataadmin/vendor/jquery/dist/jquery.min.js') }}"></script>#}

</head>
<script>
    $(document).ready(function () {
        $('.autoplay').slick({
            slidesToShow: 1,
            autoplay: true,
            autoplaySpeed: 6000,
        });
        var auto_atualiza = setInterval(function () {
            $.ajax({
                url: '{{ path('atualiza') }}',
                success: function (data) {
                    var $result = $(data).filter('#pacientes');
                    $('#pacientes').html($result);
                    $('.autoplay').slick({
                        slidesToShow: 1,
                        autoplay: true,
                        autoplaySpeed: 6000,
                    });
                }
            });
        }, 40000);
        // run the first time; all subsequent calls will take care of themselves
//        setTimeout(executeQuery, 5000);
    });

</script>

<body style="margin: 2em">
<!-- Content here -->
<div id="pacientes" class="row">
    {% block pacientes %}
    {% endblock %}
</div>
</body>

src/AppBundle/Resources/views/Default/index2.html.twig
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Acompanhamento</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          type="text/css">
    <link href="{{ asset('bundles/app/css/styles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('bundles/avanzuadmintheme/static/dev/styles/admin-lte-all.css') }}" rel="stylesheet"
          type="text/css">
    <script src="{{ asset('bundles/sonataadmin/vendor/jquery/dist/jquery.min.js') }}"></script>
</head>
<script>
    function executeQuery() {
        $.ajax({
            url: '{{ path('atualiza') }}',
            success: function(data) {

            }
        });
        setTimeout(executeQuery, 5000); // you could choose not to continue on failure...
    }

    function showPages(data) {
        $('#dados').html('<div data-slick=\'{"slidesToShow": 4, "slidesToScroll": 4}\'>\n' +
            '  <div><h3>1</h3></div>\n' +
            '  <div><h3>2</h3></div>\n' +
            '  <div><h3>3</h3></div>\n' +
            '  <div><h3>4</h3></div>\n' +
            '  <div><h3>5</h3></div>\n' +
            '  <div><h3>6</h3></div>\n' +
            '</div>');
    }

    $(document).ready(function() {
        // run the first time; all subsequent calls will take care of themselves
        setTimeout(executeQuery, 5000);
    });

</script>
<body style="margin: 2em">

<!-- Content here -->
<div class="row">
    <div class="logo text-center">
        <img src="{{ asset('bundles/app/image/acompanha101.png') }}" width="200px"/>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row" id="dados">
                {% set page_number = 0 %}
            {% for item in acompanhamentos %}
                {% set ico = item.setor.imageName %}
                {% if(loop.index is divisible by(9)) %}
                     </div>
            {% endif %}
                {% if(loop.index == 1) or loop.index is divisible by(9)%}
                    {% set page_number = page_number + 1 %}
                <div id="page{{ page_number }}">
                {% endif %}
                <div class="col-lg-4 col-sm-6 col-md-4">
                    <div class="circle-tile">
                        <a href="#">
                            <div class="circle-tile-heading dark-gray">
                                <i class="fa">
                                    <img width="50px" src="{{ asset('bundles/app/image/'~ico~'.png') }}"/>
                                </i>
                            </div>
                        </a>
                        <div class="circle-tile-content dark-gray">
                            <div class="circle-tile-number text-faded">
                                {{ item.paciente }}
                                <span id="sparklineA"></span>
                            </div>
                            <div class="circle-tile-description text-bold">
                                {{ item.setor.nome }}
                            </div>
                        </div>
                    </div>
                </div>
                    {% if(loop.last) %}
                    </div>
                    {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
</div>
</body>

src/AppBundle/Resources/views/Default/pacientes.html.twig
{% extends 'AppBundle:Default:index.html.twig' %}
{% block pacientes %}
    <div class="panel panel-default">
        <div class="logo text-center panel-heading">
            <img src="{{ asset('bundles/app/image/acompanha101.png') }}" width="200px"/>
        </div>
    </div>
    <div class="autoplay" data-slick='{"slidesToShow": 1}'>
        {% set page = 1 %}
        {% for item in acompanhamentos %}
            {% set ico = item.setor.imageName %}

            {% if(loop.index == 1) or (loop.index-1) is divisible by(number_item) %}
                <div class="panel panel-default">
                <div class="panel-body">
            {% endif %}
            <div class="col-lg-3 col-sm-6 col-md-4 col-xs-6">
                <div class="circle-tile">
                    <a href="#">
                        <div class="circle-tile-heading light-blue">
                            <i class="fa">
                                <img width="50px" src="{{ asset('bundles/app/image/'~ico~'.png') }}"/>
                            </i>
                        </div>
                    </a>
                    <div class="circle-tile-content light-blue">
                        <div class="circle-tile-number text-faded">
                            {{ item.paciente }}
                            <span id="sparklineA"></span>
                        </div>
                        <div class="circle-tile-description text-bold">
                            {{ item.setor.nome }}
                        </div>
                    </div>
                </div>
            </div>
            {% if(loop.last  or loop.index is divisible by(number_item)) %}
                </div>
                <div class="panel-footer">Página {{ page }} de {{ pages }}</div>
                </div>
                {% set page = page + 1 %}
            {% endif %}

        {% endfor %}
    </div>
{% endblock %}